### PR TITLE
Feature/dsd24 24/spoonacular api

### PR DESCRIPTION
**Pull request by AlehKhvasko**
spoonacular API -> localhost:8080/api/spoonacular/recipies
example data structure expected in post request body -> {"ingredients" :["apple", "sugar", "lemon"]}
let me know if you want something to be changed

image

### CODE REVIEW

**Review by David-Ogden-III — COMMENTED** [review]
routes/spoonacular.route.js: recipes spelled incorrectly
routes/spoonacular.route.js, line #20: Do we need a second await call if we already awaited the fetch on line #18?

**Comment by AlehKhvasko** [comment]
@David-Ogden-III , thanks for pointing that out.  Misspelled words corrected.
on line #20 we invoke .json() which returns a promise, so it's better to wait for it.

**Review by David-Ogden-III — APPROVED** [review]
Spelling error fixed and question about await was answered.

**Review by DannyRivasDev — APPROVED** [review]
Implemented Spoonacular API controller for retrieving recipes.
Fixed previous issues and code was optimized.

**Pull request merged**
