### PR TITLE
Updated Package.json and added additional .gitignore rules for unneeded folders

### PR DESCRIPTION
**Pull request by Chinzillla**
**Changes 4/2/2024:**
- added a dummy fetch request in the homepage
- Updated package.json scripts for the Client and Root Directory for developer to have ability to run Client and Server concurrently, or run server from Client Directory
- Resolved Babel Error on next.config.mjs for const
- installed missing package chart.js for Recipes folder
- Updated .env file to exclude: **.swc/** and **.next/**
- Removed Redundant .gitignore files in Client and Server

### CODE REVIEW

**Comment by David-Ogden-III** [comment]
Updates seem to accurate and do not take away functionality from the current backend state

**Comment by David-Ogden-III** [comment]
Updates seem to be accurate and do not take away functionality from the current backend state

**Review by David-Ogden-III — DISMISSED** [review]
Updates seem to be accurate and do not take away functionality from the current backend state

**Review by DannyRivasDev — DISMISSED** [review]
Great update and removal of redundant code.

**Review by David-Ogden-III — DISMISSED** [review]
Looks good

**Review by DannyRivasDev — DISMISSED** [review]
Updates made, looks good.

**Pull request merged**
