### PR TITLE
Feature/dsd24 44/login signup page

### PR DESCRIPTION
**Pull request by AlehKhvasko**
- sign-up page created
- tab title and favicon changed
- routing remodeled
- basic validation

image

### CODE REVIEW

**Review by Chinzillla — CHANGES_REQUESTED** [review]
Looks good,

Request:
- For on change on login and sign up page.js i would switch to ref hook just to optimize. We prevent tracking each user input for that field rather when submitted it will grab the whole input and check db.

(You can reference on the latest frontend branch to see implementation)

**Comment by AlehKhvasko** [comment]
useState is often used for stable state management and rerendering
as I understand useRef is more suitable for inner state management which gives you better performance, in my case for error management inside components for example
Reference:
https://stackoverflow.com/questions/76086163/what-is-better-usestate-or-useref-when-handling-multiple-form-inputs-in-react

**Comment by Chinzillla** [comment]
Thanks for the link Aleh, now i understand the difference for useRef and useState

**Review by Chinzillla — APPROVED** [review]

**Comment by Chinzillla** [comment]
I tried to run it through the deployment but for some reason the package.json is missing some components

image

**Comment by AlehKhvasko** [comment]
those errors appeared due to syntax changes when we added an underscore before the folder to exclude it from the routing system
import fixed

image

**Comment by AlehKhvasko** [comment]
conflicts resolved

**Pull request merged**
